version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "📦 chore(deps):"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
          - "@types/react-dom"
      vercel:
        patterns:
          - "@vercel/*"
          - "next"
      font:
        patterns:
          - "@fontsource/*"